[package]
name = "github-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = [ "rt-multi-thread", "macros", "fs" ] }
reqwest = { version = "0.12.15", features = [ "json" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"